server:
  port: 8090
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3320/thinkj_erp_2019?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.lgx.vo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    aggressive-lazy-loading: false #全局开启懒加载  该属性在3.4.5版本开始默认false

logging:
  path: ./logs/
  level:
    root: debug
